global:
  resolve_timeout: 2m

route:
  receiver: 'email-notifications' # Change the receiver to the email configuration

receivers:
- name: 'email-notifications' # Define the email receiver
  email_configs:
    - to: 's.siddreddy@gmail.com' # Replace with your email address
      from: 'sateesh0584@gmail.com' # Replace with the sender email address
      smarthost: 'smtp.gmail.com:587' # Replace with your SMTP server address and port
      auth_username: 'sateesh0584@gmail.com' # Replace with your SMTP username
      auth_password: 'Jan2022@' # Replace with your SMTP password
      send_resolved: true

- name: 'slack-notifications'
  slack_configs:
    - api_url: "https://hooks.slack.com/services/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"
     # Replace with your Slack Incoming Webhook URL
      channel: 'Sateesh Reddy' # Replace with the Slack channel or user where you want to send notifications
      send_resolved: true # Set to true to send resolved alerts as well

